//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFootballers.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Footballer
    {
        public int PlayersID { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 2, ErrorMessage = "Name must be atleast two letters.")]
        public string Name { get; set; }
        [Range(16, 40, ErrorMessage = "Age must be between 16 and 40.")]
        public Nullable<int> Age { get; set; }
        [Required]
        [StringLength(2, ErrorMessage = "Position must take the form GK, DF, MF or FW.")]
        public string Position { get; set; }
        [Range(0, 999, ErrorMessage = "Value must be between 0 and 999.")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Value { get; set; }
        public string ImageUrl { get; set; }
        public string VideoUrl { get; set; }
    }
}
